config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'filtrar_compromissos_tarefas', to: 'compromissos#filtrar_compromissos_tarefas', as: :filtrar_compromissos_tarefas
  
  resources :tarefas
  resources :estudos
  resources :categorium
  resources :financeiros do
    member do
      patch :pago
    end
  end
  
  resources :compromissos do
    member do
      patch :concluir
    end
  end
  
  
  
  

end

app/models/compromisso.rb
class Compromisso < ApplicationRecord
    validates :titulo, presence: true
    validates :local, presence: true
    validates :dataehora, presence: true

    validates :dataehora, uniqueness: { case_sensitive: false, on: :create, message: "Não foi possível adicionar compromisso, pois já existe um compromisso nesse dia e hora." }

    scope :filter_by_compromisso, -> (query) { where("titulo LIKE ?", "%#{query}%") }


end

app/controllers/compromissos_controller.rb
class CompromissosController < ApplicationController
    before_action :set_compromisso, only: [:show, :edit, :update, :destroy]
    def index
      @compromissos = Compromisso.all
      
      if params[:query].present?
        @compromissos = @compromissos.where('titulo LIKE ?', "%#{params[:query]}%")
      end
  
      if params[:status].present?
        if params[:status] == 'concluidos'
          @compromissos = @compromissos.where(status: true)
        elsif params[:status] == 'nao_concluidos'
          @compromissos = @compromissos.where(status: false)
        end
      end
  
      if params[:start_date].present? && params[:end_date].present?
        start_date = DateTime.parse(params[:start_date])
        end_date = DateTime.parse(params[:end_date])
        @compromissos = @compromissos.where(dataehora: start_date..end_date)
      elsif params[:start_date].present?
        start_date = DateTime.parse(params[:start_date])
        @compromissos = @compromissos.where('dataehora >= ?', start_date)
      elsif params[:end_date].present?
        end_date = DateTime.parse(params[:end_date])
        @compromissos = @compromissos.where('dataehora <= ?', end_date)
      end
    end

      def concluidos
        @compromissos = Compromisso.where(status: true)
      end
      
    
    
    def show
    end
  
    def new
      @compromisso = Compromisso.new
    end
  
    def create
      @compromisso = Compromisso.new(compromisso_params)
  
      respond_to do |format|
        if @compromisso.save
          format.html { redirect_to @compromisso, notice: 'Compromisso criado com sucesso.' }
          format.json { render :show, status: :created, location: @compromisso }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @compromisso.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def edit
    end
  
    def concluir
      @compromisso = Compromisso.find(params[:id])
      
      if @compromisso.update(status: true)
        redirect_to compromissos_path, notice: 'Compromisso concluído com sucesso.'
      else
        redirect_to compromissos_path, alert: 'Não foi possível concluir o compromisso.'
      end
    end
    

    def update
      respond_to do |format|
        if @compromisso.update(compromisso_params, status: true)
          format.html { redirect_to @compromisso, notice: 'Compromisso atualizado com sucesso!' }
          format.html { redirect_to compromissos_path, notice: 'Compromisso concluído com sucesso.'
        }
          format.json { render :show, status: :ok, location: @compromisso }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @compromisso.errors, status: :unprocessable_entity }
        end
      end
    end
  
    
  
    def destroy
      @compromisso.destroy
      respond_to do |format|
        format.html { redirect_to compromissos_url, notice: 'Compromisso apagado com sucesso.' }
        format.json { head :no_content }
      end
    end
  
    private
  
    def set_compromisso
      @compromisso = Compromisso.find(params[:id])
    end
  
    def compromisso_params
      params.require(:compromisso).permit(:titulo, :local, :dataehora)
    end
  end

  

app/helpers/compromissos_helper.rb
module CompromissosHelper
end

app/views/compromissos/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DailyPlanning - Novo Compromisso</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f4f4f9;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            font-family: 'Alata', sans-serif;
        }

        .form-container {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 500px;
            width: 100%;
        }

        .form-container h2 {
            color: #333333;
            margin-bottom: 20px;
        }

        .form-container .field {
            margin-bottom: 15px;
        }

        .form-container label {
            color: #666666;
            margin-bottom: 5px;
        }

        .form-container input[type="text"],
        .form-container input[type="datetime-local"] {
            border: 1px solid #dddddd;
            border-radius: 5px;
            width: 100%;
            padding: 10px;
            transition: border-color 0.3s;
        }

        .form-container input[type="text"]:focus,
        .form-container input[type="datetime-local"]:focus {
            border-color: #B7D3FA;
        }

        .form-container .actions {
            display: flex;
            justify-content: center;
        }

        .form-container .actions input[type="submit"] {
            background-color: #D077AF;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .form-container .actions input[type="submit"]:hover {
            background-color: #B7D3FA;
        }

        #error_explanation {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
        }

        #error_explanation h2 {
            margin-top: 0;
        }

        #error_explanation ul {
            list-style: none;
            padding-left: 0;
        }

        #error_explanation ul li {
            margin-left: 0;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <%= form_with(model: @compromisso, local: true, class: "form") do |form| %>
            <h2>Novo Compromisso</h2>
            <% if @compromisso.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@compromisso.errors.count, "erro") %> impedem que este compromisso seja salvo:</h2>
                    <ul>
                        <% @compromisso.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="field">
                <%= form.label :titulo, "Título" %>
                <%= form.text_field :titulo, class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :local, "Local" %>
                <%= form.text_field :local, class: "form-control" %>
            </div>

            <div class="field">
                <%= form.label :dataehora, "Data e Hora" %>
                <%= form.datetime_local_field :dataehora, class: "form-control" %>
            </div>

            <div class="actions">
                <%= form.submit "Salvar", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>

    <!-- Bootstrap JS (opcional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/compromissos/concluidos.html.erb
<%# app/views/compromissos/concluidos.html.erb %>
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- ... meta tags e links de estilo ... -->
</head>
<body>
  <main class="container my-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="mb-0">Compromissos Concluídos</h1>
        <%= link_to 'Novo Compromisso', new_compromisso_path, class: "button" %>
    </div>

    <div class="row g-4">
        <% @compromissos.each do |compromisso| %>
        <div class="col-md-6 col-lg-4">
            <section class="card">
                <img src="https://img.freepik.com/free-photo/calendar-with-date-schedule-alarm-clock_107791-15677.jpg" class="card-img-top" alt="Ilustração de compromissos">
                <div class="card-body">
                    <h5 class="card-title"><%= compromisso.titulo %></h5>
                    <p class="card-text"><strong>Local:</strong> <%= compromisso.local %></p>
                    <p class="card-text"><strong>Data e Hora:</strong> <%= compromisso.dataehora.strftime("%d/%m/%Y %H:%M") %></p>
                    <p class="card-text"><strong>Status:</strong> <%= compromisso.status ? "Concluída" : "Não concluída" %></p>

                    <div class="d-flex justify-content-between align-items-center">
                        <%= link_to 'Mostrar', compromisso, class: "btn btn-sm btn-outline-primary" %>
                        <%= link_to 'Editar', edit_compromisso_path(compromisso), class: "btn btn-sm btn-outline-secondary" %>
                        <span class="btn btn-sm btn-outline-success">Concluído</span>
                    </div>
                </div>
            </section>
        </div>
        <% end %>
    </div>

    <%= link_to 'Voltar', root_path %>
  </main>
  <!-- Scripts Bootstrap -->
</body>
</html>

app/views/compromissos/edit.html.erb
<h1>Editar Compromisso</h1>

<%= render 'form', compromisso: @compromisso %>

<%= link_to 'Voltar', compromissos_path %>

app/views/compromissos/filtrar.html.erb
<h1>Resultados da Filtro</h1>

<h2>Compromissos</h2>
<ul>
  <% @compromissos.each do |compromisso| %>
    <li><%= compromisso.titulo %></li>
  <% end %>
</ul>

<h2>Tarefas</h2>
<ul>
  <% @tarefas.each do |tarefa| %>
    <li><%= tarefa.titulo %></li>
        <li><%= tarefa.descricao %></li>

  <% end %>
</ul>

app/views/compromissos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- ... meta tags e links de estilo ... -->
</head>
<body>
  <main class="container my-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="mb-0">Compromissos</h1>
        <%= link_to 'Novo Compromisso', new_compromisso_path, class: "button" %>
    </div>

    <div class="search-container mb-4">
    <%= form_with url: compromissos_path, method: :get, class: "form-inline" do |form| %>
        <div class="input-group">
            <%= form.label :query, "Filtrar por:", class: "input-group-text" %>
            <%= form.text_field :query, class: "form-control search-input", placeholder: "Filtrar compromissos" %>
            <%= form.select :status, options_for_select([['Todos', ''], ['Concluídos', 'concluidos'], ['Não Concluídos', 'nao_concluidos']]), {}, class: "form-select" %>
            <%= form.datetime_local_field :start_date, class: "form-control" %>
            <%= form.submit "Filtrar", class: "btn btn-outline-primary" %>
        </div>
    <% end %>
</div>


   <div class="row g-4">
  <% @compromissos.each do |compromisso| %>
    <div class="col-md-6 col-lg-4">
      <section class="card">
        <img src="https://img.freepik.com/free-photo/calendar-with-date-schedule-alarm-clock_107791-15677.jpg" class="card-img-top" alt="Ilustração de compromissos">
        <div class="card-body">
          <h5 class="card-title"><%= compromisso.titulo %></h5>
          <p class="card-text"><strong>Local:</strong> <%= compromisso.local %></p>
          <p class="card-text"><strong>Data e Hora:</strong> <%= compromisso.dataehora.strftime("%d/%m/%Y %H:%M") %></p>
          <p class="card-text"><strong>Status:</strong> <%= compromisso.status ? "Concluída" : "Não concluída" %></p>

          <div class="d-flex justify-content-between align-items-center">
            <%= link_to 'Mostrar', compromisso, class: "btn btn-sm btn-outline-primary" %>
            <%= link_to 'Editar', edit_compromisso_path(compromisso), class: "btn btn-sm btn-outline-secondary" %>
            <% if compromisso.status %>
              <span class="btn btn-sm btn-outline-success">Concluído</span>
            <% else %>
              <%= button_to 'Concluir', concluir_compromisso_path(compromisso), method: :patch, data: { confirm: 'Tem certeza?' }, class: "btn btn-sm btn-outline-success" %>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  <% end %>
</div>


    <%= link_to 'Voltar', root_path %>
  </main>

  <!-- Scripts Bootstrap -->
</body>
</html>

app/views/compromissos/new.html.erb
<h1>Novo Compromisso</h1>

<%= render 'form', compromisso: @compromisso %>

<%= link_to 'Voltar', compromissos_path %>
    

app/views/compromissos/show.html.erb
<p>
  <strong>Título:</strong>
  <%= @compromisso.titulo %>
</p>

<p>
  <strong>Local:</strong>
  <%= @compromisso.local %>
</p>

<p>
  <strong>Data e Hora:</strong>
  <%= @compromisso.dataehora %>
</p>

<%= link_to 'Editar', edit_compromisso_path(@compromisso) %> |
<%= link_to 'Voltar', compromissos_path %>