config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'filtrar_compromissos_tarefas', to: 'compromissos#filtrar_compromissos_tarefas', as: :filtrar_compromissos_tarefas
  
  resources :tarefas
  resources :estudos
  resources :categorium
  resources :financeiros do
    member do
      patch :pago
    end
  end
  
  resources :compromissos do
    member do
      patch :concluir
    end
  end
  
  
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
       
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Gerencie seus compromissos diários de forma eficiente com o DailyPlanning.">
    <meta name="keywords" content="DailyPlanning, gerenciamento de compromissos, finanças pessoais, estudos">
    <title>DailyPlanning - Gerencie seus compromissos diários</title>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <style>
        * {
    font-family: 'Alata', sans-serif;
    font-weight: 400;
    font-style: normal;
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    background-color: #f4f4f9;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
}

.navbar {
    background-color: #B7D3FA;
    height: 50px;
    border-radius: 3px;
    color: #D077AF;
    display: flex;
    align-items: center;
    padding: 0 10px;
    width: 100%;
}

#logo {
    height: 30px;
    color: #D077AF;
    margin-right: auto;
}

.search-container {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 600px;
    height: 100%;
}

.search {
    width: 350px;
    background-color: #B7D3FA;
    align-items: center;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    margin-top: 20px;
    transition: transform 0.3s;
    display: flex;
    justify-content: center;
    padding: 10px;
}

.search:hover {
    transform: scale(1.05);
}

.barra-pesquisa {
    width: 250px;
    background-color: #B7D3FA;
    border: none;
    border-radius: 10px;
    padding: 5px 10px;
}

.barra-pesquisa::placeholder {
    color: #666;
}

.barra-pesquisa:focus {
    outline: none;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
}

.barra-pesquisa-label {
    background-color: #B7D3FA;
    border: none;
    margin-right: 10px;
    padding: 5px 10px;
    border-radius: 5px;
}

.button-filtrar {
    background-color: #D077AF;
    color: white;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
}

.button-filtrar:hover {
    background-color: #c067a5;
}

.card {
    background-color: #ffffff;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    overflow: hidden;
    transition: transform 0.3s;
}

.card:hover {
    transform: scale(1.05);
}

.card img {
    width: 100%;
    height: auto;
    border-bottom: 1px solid #eeeeee;
}

.card-body {
    padding: 20px;
}

.card-title {
    font-size: 1.2rem;
    margin-bottom: 10px;
    color: #333333;
}

.card-text {
    color: #666666;
    font-size: 0.9rem;
    line-height: 1.6;
}

.button {
    display: inline-block;
    padding: 8px 16px;
    background-color: #D077AF;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.button:hover {
    background-color: #c067a5;
}

footer {
    background-color: #B7D3FA;
    color: #D077AF;
    padding: 20px 0;
    text-align: center;
    width: 100%;
    margin-top: auto;
}

.footer-links {
    display: flex;
    justify-content: center;
    list-style: none;
    padding: 0;
}

.footer-links li {
    margin: 0 10px;
}

.footer-links a {
    color: #D077AF;
    text-decoration: none;
    transition: color 0.3s;
}

.footer-links a:hover {
    color: #7e9bd7;
}

    </style> <!-- Seu CSS personalizado aqui -->

</head>
<body>
        <div class="search-container mb-4">
        <%= form_with url: filtrar_compromissos_tarefas_path, method: :get, class: "form-inline" do |form| %>
            <div class="input-group">
                <%= form.label :query, "Filtrar por:", class: "input-group-text" %>
                <%= form.text_field :query, class: "form-control search-input", placeholder: "Filtrar compromissos" %>
                <%= form.submit "Filtrar", class: "btn btn-outline-primary" %>
            </div>
        <% end %>
    </div>
    <main class="container my-4">
        <div class="row g-4">
            <div class="col-md-6 col-lg-4">
                <section class="card">
                    <img src="https://img.freepik.com/free-photo/calendar-with-date-schedule-alarm-clock_107791-15677.jpg" class="card-img-top" alt="Ilustração de compromissos">
                    <div class="card-body">
                        <h5 class="card-title">Meus compromissos</h5>
                        <p class="card-text">Gerencie seus compromissos de forma eficiente com o DailyPlanning.</p>
                        <button class="button"><%= link_to "Compromissos", compromissos_path %> </button>
                    </div>
                </section>
            </div>
            <div class="col-md-6 col-lg-4">
                <section class="card">
                    <img src="https://img.freepik.com/free-photo/3d-illustration-calendar-page-clock-money_107791-15945.jpg" class="card-img-top" alt="Ilustração de finanças">
                    <div class="card-body">
                        <h5 class="card-title">Minhas Finanças</h5>
                        <p class="card-text">Gerencie suas finanças pessoais de forma eficiente com o DailyPlanning.</p>
                        <button class="button"><%= link_to "Financeiro", financeiros_path	 %> </button>
                    </div>
                </section>
            </div>
            <div class="col-md-6 col-lg-4">
                <section class="card">
                    <img src="https://img.freepik.com/free-photo/3d-books-notepad-pencil-pen-eraser_107791-15690.jpg" class="card-img-top" alt="Ilustração de estudos">
                    <div class="card-body">
                        <h5 class="card-title">Estudos</h5>
                        <p class="card-text">Gerencie seus estudos de forma organizada com o DailyPlanning.</p>
                        <button class="button"><%= link_to "Estudo", estudos_path %> </button>
                    </div>
                </section>
            </div>
            <div class="col-md-6 col-lg-4">
                <section class="card">
                    <img src="https://img.freepik.com/free-photo/3d-render-checklist-alarm-clock-project-plan_107791-15663.jpg" class="card-img-top" alt="Ilustração de lista de tarefas">
                    <div class="card-body">
                        <h5 class="card-title">Minhas tarefas</h5>
                        <p class="card-text">Organize suas tarefas diárias com eficiência com o DailyPlanning.</p>
                        <button class="button"><%= link_to "Tarefas", tarefas_path %> </button>
                    </div>
                </section>
            </div>
        </div>
    </main>
</body>
</html>