config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'filtrar_compromissos_tarefas', to: 'compromissos#filtrar_compromissos_tarefas', as: :filtrar_compromissos_tarefas
  
  resources :tarefas
  resources :estudos
  resources :categorium
  resources :financeiros do
    member do
      patch :pago
    end
  end
  
  resources :compromissos do
    member do
      patch :concluir
    end
  end
  
  
  
  

end

app/models/estudo.rb
class Estudo < ApplicationRecord
    validates :titulo, presence: true
    validates :descricao, presence: true

end

app/controllers/estudos_controller.rb
class EstudosController < ApplicationController
    before_action :set_estudo, only: [:show, :edit, :update, :destroy]
  
    def index
      @estudos = Estudo.all
    end
  
    def show
    end
  
    def new
      @estudo = Estudo.new
    end
  
    def create
      @estudo = Estudo.new(estudo_params)
      if @estudo.save
        redirect_to @estudo, notice: 'Estudo foi criado com sucesso.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @estudo.update(estudo_params)
        redirect_to @estudo, notice: 'Estudo foi atualizado com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @estudo.destroy
      redirect_to estudos_url, notice: 'Estudo foi excluído com sucesso.'
    end
  
    private
  
    def set_estudo
      @estudo = Estudo.find(params[:id])
    end
  
    def estudo_params
      params.require(:estudo).permit(:titulo, :descricao)
    end
  end
  

app/helpers/estudos_helper.rb
module EstudosHelper
end

app/views/estudos/_form.html.erb
<%= form_with(model: @estudo, local: true) do |form| %>
  <% if @estudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estudo.errors.count, "error") %> proibiu este estudo de ser salvo:</h2>

      <ul>
        <% @estudo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/estudos/edit.html.erb
<h1>Editar Estudo</h1>
<%= render 'form', estudo: @estudo %>
<%= link_to 'Voltar', estudo_path(@estudo) %>

app/views/estudos/index.html.erb
<h1>Estudos</h1>

<%= link_to 'Novo Estudo', new_estudo_path %>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudos.each do |estudo| %>
      <tr>
        <td><%= estudo.titulo %></td>
        <td><%= estudo.descricao %></td>
        <td><%= link_to 'Mostrar', estudo %></td>
        <td><%= link_to 'Editar', edit_estudo_path(estudo) %></td>
        <td><%= link_to 'Excluir', estudo, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/estudos/new.html.erb
<h1>Novo estudo</h1>

<%= render 'form', estudo: @estudo %>

<%= link_to 'Voltar', estudos_path %>
    

app/views/estudos/show.html.erb
<h1><%= @estudo.titulo %></h1>
<p><%= @estudo.descricao %></p>

<%= link_to 'Editar', edit_estudo_path(@estudo) %> |
<%= link_to 'Voltar', estudos_path %>